services:
  postgres:
    image: postgres:18.3
    container_name: hl_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: social_user
      POSTGRES_PASSWORD: social_pass
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U social_user -d social"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - shared-network



  profile:
    build: .
    container_name: profile
    restart: unless-stopped
    ports:
      - "8083:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: social
      DB_USER: social_user
      DB_PASSWORD: social_pass
      SERVER_ADDR: :8080
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: ${RABBIT_PORT:-5672}
      RABBIT_USERNAME: ${RABBIT_USERNAME:-billing}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD:-billing}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shared-network

volumes:
  pgdata:

networks:
  shared-network:
    external: true
    name: shared-network